coverage:
  status:
    project:
      default:
<<<<<<< HEAD
        target: 80%
=======
        target: 90%
>>>>>>> origin/release/v0.5.0-alpha
        threshold: 0.5%
        base: auto
        if_no_uploads: error
        if_not_found: error
        if_ci_failed: error
        only_pulls: false
    patch:
      default:
<<<<<<< HEAD
        target: 80%
=======
        target: 90%
>>>>>>> origin/release/v0.5.0-alpha
        threshold: 0.5%
        base: auto
        if_no_uploads: error
        if_not_found: error
        if_ci_failed: error
        only_pulls: false
